services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped

  frontend:
    hostname: frontend
    build: ./frontend/
#    ports:
#      - 5173:5173

  db:
    hostname: db
    image: mysql:5.7
    # volumes:
    #   - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${BWB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: best-with-butter
      MYSQL_USER: ${BWB_MYSQL_USER}
      MYSQL_PASSWORD: ${BWB_MYSQL_PASSWORD}
#    ports:
#      - 3306:3306

  backend:
    hostname: backend
    depends_on:
      - db
    build: ./backend/
#    ports:
#      - 5000:80

# volumes:
#   database:
